### ISSUE TITLE
MultiIndexSet

### ISSUE THREAD

**Issue by szabo137** [MultivariantToolkit/MultivariateInterpolation.jl#1]
# Generalities

The set of all exponent vectors of all monomials on a multivariate polynomial is called _multi index set_. The number of exponent vectors in the multi index set is equal to the number of terms of the polynomial. The number of entries of any exponent vector on a multi index set is equal to the dimension of the domain space of the polynomial. 

# Implementation in `minterpy`

In `minterpy==0.1.3` the multi index set is described in `core/multi_index.py` (see [here](https://github.com/casus/minterpy/blob/main/src/minterpy/core/multi_index.py)). Some functionality is stored in `core/utils.py`. 

There, a multi index set is described by objects of a class `MultiIndexSet`.

### `exponents`

The `exponents` attribute stores the set of exponent vectors as a 2D `numpy.ndarray`, where the first axis denotes the number of monomials and the second axis denotes the spatial dimension, i.e. the dimension of the domain space.

### `lp_degree`

The attribute `lp_degree` saves the degree of the norm used on the multi index set. 

### `exponents_completed`

The attribute `exponents_completed` saves a version of `exponents`, which is lexicographically complete. This a lazy attribute. 

### `is_complete`

The attribute `is_complete` saves the Boolean value of the stored exponent set is lexicographically complete. 

### `spatial_dimension`

The attribute `spatial_dimension` saves the dimension of the domain space of the polynomial. 

### default contructor

Gets the exponent vector set as a 2D `numpy.ndarray` and the `lp_degree` as a `float`, which is optional. Some checks are performed and verifications are asserted. 

### `from_degree`

Gets `dim` the spatial dimension, `deg` the polynomial degree and `lp` the degree of the lp-norm on the exponent vectors. The exponents are constructed directly in lexicographically order, where each exponent vector `v` obeys `norm(v,lp)<=deg`. Then the default constructor is called. 

### `expand_dim(self, dim)`

Expands the second axis of `self.exponents` up to `dim`. 

### `contains_these_exponents(self, vectors)`

Checks if a given exponent vector set `vectors` is in `self.exponents`. 

Additionally, there are member functions `is_sub_index_set_of` and `is_super_index_set_of` which check for the sub- and super-set property by calling `contains_these_exponents` with arguments in the respective order. 

### `add_exponents(self, exponents)`

Adds a given set of exponent vectors `exponents` to `self.exponents`.

### `make_complete(self)`

Creates a new version with the properties of `self`, but with a completed exponent vector set. 

# Suggested enhancements

## Naming

The name `MultiIndexSet` is somewhat misleading, because it is not a set of multi indices, but a set of vectors of exponents. Therefore, a renaming to `ExponentVectors` seems appropriate. 

## Memory 

The python version stores the whole exponent vector set in RAM, which is very memory consuming. A solution build on a similar data layout, i.e. a 2D array, could circumvent this by using iterators and lazy evaluation of the exponent vectors. 

# Todos 

- [ ] Implement `ExponentVectors` data type with default constructor 
- [ ] Implement properties `spatial_dimension` and  `polynomial_degree` as interface functions with the keyword argument `lp` for the used norm 
- [ ] Implement fast generation of exponent vectors from `(dim, deg; lp)`

# Optional todos 

- [ ] Implement `is_complete` which checks for lexicographic completeness
- [ ] Implement `make_complete`
- [ ] Implement `is_subset` and `is_superset`
- [ ] Implement `is_lexsorted` which checks of the exponent vectors are lexicographically ordered 
- [ ] Implement `lexsort` which reorders the exponent vectors in lexicographical order

**Comment by szabo137** [comment]
# Todos 

- [ ] Implement `ExponentVectors` data type with default constructor 
- [ ] Implement properties `spatial_dimension` and  `polynomial_degree` as interface functions with the keyword argument `lp` for the used norm 
- [ ] Implement fast generation of exponent vectors from `(dim, deg; lp)`

# Optional todos 

- [ ] Implement `is_complete` which checks for lexicographic completeness
- [ ] Implement `make_complete`
- [ ] Implement `is_subset` and `is_superset`
- [ ] Implement `is_lexsorted` which checks of the exponent vectors are lexicographically ordered 
- [ ] Implement `lexsort` which reorders the exponent vectors in lexicographical order
